---
name: Enforce PR labels

on:
  workflow_call:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]

permissions: read-all

jobs:
  enforce-label:
    if: ${{ contains(github.event.*.labels.*.name, 'hold') || contains(github.event.*.labels.*.name, 'needs-qa') }}
    name: Enforce label
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Check for label
        run: |
          echo "PRs with the hold or needs-qa labels cannot be merged"
          echo "### :x: PRs with the hold or needs-qa labels cannot be merged" >> $GITHUB_STEP_SUMMARY
          exit 1
